movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

props/urls.py
from django.urls import path
from . import views

app_name = 'props'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:prop_id>', views.detail, name='detail')
]

vidly3/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from api.models import PropResource
from . import views

movie_resource = MovieResource()
prop_resource = PropResource()

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('props/', include('props.urls')),
    path('api/', include(movie_resource.urls)),
    path('api/', include(prop_resource.urls)),
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
from props.models import Prop


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'


class PropResource(ModelResource):
    class Meta:
        queryset = Prop.objects.all()
        resource_name = 'props'

movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

props/models.py
from django.db import models
from django.utils import timezone


class Taste(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Prop(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    taste = models.ForeignKey(Taste, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse, Http404
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

props/views.py
from django.http import HttpResponse, Http404
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Prop


def index(request):
    props = Prop.objects.all()
    return render(request, 'props/index.html', {'props': props})


def detail(request, prop_id):
    prop = get_object_or_404(Prop, pk=prop_id)
    return render(request, 'props/detail.html', {'prop': prop})

vidly3/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd class="detail-content">{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd class="detail-content">{{ movie.genre }}</dd>
    <dt>Stock</dt>
    <dd class="detail-content">{{ movie.number_in_stock }}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
      </td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

props/templates/props/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd class="detail-content">{{ prop.title }}</dd>
    <dt>Genre</dt>
    <dd class="detail-content">{{  prop.taste }}</dd>
    <dt>Stock</dt>
    <dd class="detail-content">{{ prop.number_in_stock }}</dd>
</dl>
{% endblock %}

props/templates/props/index.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Taste</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for prop in props %}
    <tr>
      <td>
        <a href="{% url 'props:detail' prop.id %}">{{ prop.title }}</a>
      </td>
      <td>{{ prop.taste }}</td>
      <td>{{ prop.number_in_stock }}</td>
      <td>{{ prop.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&family=Montserrat:wght@400&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Vidly</title>
  </head>
  <body>
    <!-- Navigation or header -->
    <nav class="navbar">
      <!-- Home button -->
      <a href="{% url 'home' %}" class="home-button">Home</a>

  </nav>
    <div
      class="video-related-background"
      style="background-image: url('{% static 'img/videotape.jpg' %}')"
    >
  </div>


      <div>
        <a class="header" href="#">Vidly</a>
      </div>

    <!-- As a heading -->
      <div>
        <h1 class="subtitle">Vidly Movies & Props</h1>
      </div>
    <div class="spacing">
    </div>
    <main class="">{% block content %} {% endblock %}</main>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <a class="button" href="{% url 'movies:index' %}">Movies</a>
  <a class="button" href="{% url 'props:index' %}">Props</a>
{% endblock %}